init:
- git config --global core.autocrlf true
install:
  - ps: Install-Product node 8 x64
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: 'off'
deploy: 'off'
os: Visual Studio 2017 Preview
build_script:
  - dotnet build Blazor.sln
before_test:
  - choco install googlechrome --ignore-checksum
  - npm install -g selenium-standalone
  - selenium-standalone install
  - ps: $SeleniumProcess = Start-Process "selenium-standalone" -ArgumentList "start" -PassThru
test_script:
  - dotnet test test\AllTests.proj
after_test:
  - ps: Stop-Process -Id $SeleniumProcess.Id
